### ISSUE TITLE
AAPT exited with error code 1

### ISSUE THREAD

**Issue by Ardumania** [Calsign/APDE#15]
Hello.

I'm trying to use APDE ver 0.3.3 but I cant.

When trying to compile appear this error:

*Initializing build sequence....*
*Deletec old build folder*
*Injected lod broadcaster*
*Detected architecture armeabi-v7a*

*Packaging resources with AAPT...*
*AAPT exited with error code 1*

Device is a Sony Xperia M2 with Android 4.4.4

With ver 0.3.2 worked prefectly and enjoyed very much of APDE.

Best regards from Spain.

**Comment by Calsign** [comment]
I apologize for not responding for so long. I have a potential solution, but I haven't had enough time to get my act together and publish a release. I do realize that a lot of users are experiencing this issue, but I really mean it when I say that I have had practically no time.

Anyhow, this bug is very closely related to issue #10, so I am closing this issue and merging discussion into there.
