### ISSUE TITLE
Editor clears on simultaneous Power button and rotation activation.

### ISSUE THREAD

**Issue by zoombeani** [Calsign/APDE#28]
When typing code into the editor in portrait mode and then simultaneously* hitting the power button and rotating the device to activate the auto rotate function in Android will clear all contents of the editor. Upon waking the device back up the editor is empty and the undo function is greyed out and reloading the sketch loads the editor in an empty state. *Does not have to be frame perfect simultaneous, there's some wiggle room.

**Comment by Calsign** [comment]
@zoombeani I suspect that this bug is the same as #24, for which I have a fix that I haven't gotten around to releasing yet. I am nearly certain that this is a duplicate, but can you please confirm? You should not experience the bug after updating to the bugfix version, downloadable from DropBox:

https://www.dropbox.com/s/zme56ej17woblaz/APDE-bugfix-2017-01-24.apk?dl=0

Note that you may have to do a full reinstall (uninstall APDE first) and/or restart your device before the fix will work. I don't know why this would be the case but the user in that other bug report had to do these steps at some point in time during the debug process. I don't recommend trying these at first, but only if the initial fix fails.

**Comment by zoombeani** [comment]
I read the title for #24 but ignored it because of the "External Storage" language as I do not have an SD card. I now see in the APDE settings that external storage does not simply refer to an SD card. Since I move items to the Sketchbook #24 definitely applies.

So I downloaded the bugfix apk from the supplied dropbox link:
1. I just installed (updated) the apk over the old version. I was able to recreate the issue.
2. I uninstalled and reinstalled (without restarting). I was able to recreate the issue.
3. I uninstalled, restarted, reinstalled, and restarted. I am still able to recreate the issue.

Thanks for your attention on this.

**Comment by Calsign** [comment]
@zoombeani I don't know why the bug is still occurring. I am unable to reproduce the bug myself, so I am going to have to ask you to reproduce it with new APKs as I did in #24 - if you are willing of course. It would be much appreciated.

I have uploaded an APK with the latest changes to DropBox:

https://www.dropbox.com/s/8gsmdlfaydtyf4f/APDE-2017-02-01.apk?dl=0

This version doesn't have a potential fix for your bug, but it does preserve the console output across screen orientation changes (the previous fix version didn't) which will show you the error message or stack trace if there is one. If there is such a message then that is the key to fixing the bug.

Also, please go to Settings > General and enable "Global Verbose Output" under Debug. By default some console output when APDE is launched is hidden because there is sometimes unnecessary/distracting output from the examples update checks. The error message related to this new code deletion bug may be being masked as well, so please enable "Global Verbose Output".

**Comment by Calsign** [comment]
I am merging this bug into #24 as they appear to be the same.
