### ISSUE TITLE
Apk made but not working!

### ISSUE THREAD

**Issue by s-mv** [Calsign/APDE#32]
My Samsung phone has this problem. Ver. 4.1.2.
The project makes apk but then crashes it 96% times... I am a teen can't buy a hi-end phone. This is a critical bug.

**Comment by LunarWatcher** [comment]
Why does it crash? With 99% guarantee, this isn't an issue with APDE but with your app. Grab the error logs and see whether there's something that points to your code or not.

**Comment by StinkyVoid** [comment]
Mr. LunarWatcher, I am very sorry but what's wrong in this:

void setup(){
  size(displayWidth,displayHeight);
  noStroke();
}
void draw(){
  background(176);
  rect(mouseX,mouseY,width/23,width/23);
}
void mousePressed(){
  fill(255,0,0);
}

**Comment by LunarWatcher** [comment]
I have no clue, because it's taken out of context. [Read this](https://stackoverflow.com/help/mcve). Even though this isn't Stack Overflow, an MCVE is a very good way to help others reproduce problems and track the source

**Comment by StinkyVoid** [comment]
Great but not very useful

**Comment by StinkyVoid** [comment]
LunarWatcher scold joe ;-)

**Comment by Calsign** [comment]
@LunarWatcher Normally your advice that the error is caused by the sketch itself would be accurate, but in this case there is no good reason for the code provided (which is an MCVE) to fail. This does indeed appear to be an APDE bug.

@StinkyVoid What error output do you receive - if any? Does the sketch crash at the same rate when you run it from the Android launcher instead of from APDE? Do the examples also crash? (Some very simple examples can be found under Basics.)

I need more information to understand what is going on - and that starts by answering the questions above.

As a sneaking suspicion, though - does the problem persist if you go to Settings > Build and disable "Inject Log Broadcaster"?

**Comment by StinkyVoid** [comment]
All examples crash! And they crash from both APDE and Android launchers. I
get an error on APDE: java.lang.NullPointerException.
Buty program is purely working when I change it a bit a try it on my pc!
What is this big problem... The world wants to know!

**Comment by Calsign** [comment]
@StinkyVoid What is the full stack trace in the console? Also, did you try the settings change that I suggested above?

**Comment by s-mv** [comment]
It's been 4 years and this issue's still open. Please allow me to sigh as I read my past self's unhelpful/non-existent responses.
I don't really know what went wrong and can't remember much from back then really, but I think I should just close this issue since it's really irrelevant by now.
