### ISSUE TITLE
Version 0.5.0-pre2 does not work on KitKat

### ISSUE THREAD

**Issue by EmmanuelPil** [Calsign/APDE#43]
Installed on my Samsung tablet Tab E with KitKat 4.4 even the most basic examples will compile but not run. A message is shown that rhe sketch stopped, and no error is given in the console with all verbose output enabled. I deletted all traces of previous versions with (rooted) SD Maid. I've repeted this several times.

**Comment by EmmanuelPil** [comment]
When reinstalling previous apde version, simple sketches will run, but more complex ones, with a lot of tabs will all give the error aapt 1.  Loading saved, renamed copies from pc will run on device again.

**Comment by EmmanuelPil** [comment]
On my phone with lollipop 5.1 It is working well.

**Comment by Calsign** [comment]
Strange. I will see if I can replicate this with a 4.4 emulator, I should be able to debug it with LogCat.

The old version of APDE should still work. My best guess for why PC sketches work but others don't is the manifest. What happens when you delete the sketch manifest file so that it is regenerated?

**Comment by Calsign** [comment]
This seems to be an issue with support library compatibility. [StackOverflow](https://stackoverflow.com/q/35622438/). I should be able to fix it by adjusting library versions.

**Comment by Calsign** [comment]
Adding the option `--no-version-vectors` to AAPT, as described on the [Android Developers blog](https://android-developers.googleblog.com/2016/02/android-support-library-232.html), appears to have solved the first crash (`XMLPullParserException` described in the StackOverflow link above).

However, I am now getting a second crash on 4.4, a `VerifyException` similar to an [issue on the Android mode repo](https://github.com/processing/processing-android/issues/457). Not fun.

**Comment by Calsign** [comment]
This should be fixed with bb0ed8b. There were two problems, both resolved, and I can now build sketches successfully in a 4.4 emulator.

@EmmanuelPil Please try this [bugfix APK](https://www.dropbox.com/s/yih9njxr3txr8vj/APDE-bugfix-2018-06-03.apk?dl=0). If all is good, I will roll the changes into the next pre-release.

**Comment by EmmanuelPil** [comment]
Great, working well, no problems today!

**Comment by EmmanuelPil** [comment]
Just a note. I don't understand why you eliminated the  redo button, and used it in the menu instead.
I use it a lot, and now it is more difficult.

**Comment by Calsign** [comment]
@EmmanuelPil On my phone, undo and redo are always in the overflow menu. The number of buttons displayed depends on the device. The fact that redo is no longer present for you is a side effect of my adding the target selection button (between run and stop).

It would be nice to have undo and redo present at all times, even on phones. I will look into ways to make these buttons more accessible - perhaps moving them out of the action bar.

**Comment by EmmanuelPil** [comment]
Thank you for the answer and the great work on APDE. I really appreciate that
