### ISSUE TITLE
Manifest settings get reset in 0.5.0

### ISSUE THREAD

**Issue by ShreerangV** [Calsign/APDE#45]
Whenever I use Bluetooth for my app, the orientation and version preferences go back to default, along with min SDK version.
Not a big problem, but still a problem.

**Comment by Calsign** [comment]
This is actually a thornier problem than I thought it was. The way that APDE currently tries to do things is very buggy, causing the manifest to get overwritten every build. (There are other subtleties but it isn't important.)

Desktop Android mode deals with this by rewriting the manifest when the user switches the component/target (app, wallpaper, watch face, or VR). The manifest actually gets scrapped and rewritten, and things like the app version and orientation preferences seem to go with it. The only thing that gets copied over is the permissions.

So a logical solution is to copy over not just the permissions, but all of the other manifest settings that we care about. I had tried to implement it this way, but clearly it isn't working.

There are, however, problems with this solution. Some targets have built-in permissions (watch face uses WAKE_LOCK and VR uses VIBRATE and READ_EXTERNAL_STORAGE). On the desktop, when you switch from app, with no permissions, to watch face, WAKE_LOCK gets added automatically. But when you switch back to app, WAKE_LOCK is still there. This is unacceptable for me because I want users to be able to switch back and forth between different targets on the fly without accumulating unwanted permissions.

Thus I think that the best solution is to define a special sketch properties file that holds all of the desired manifest attributes: display name, version code, version name, min sdk, target sdk, orientation, and permissions - and perhaps others in the future. Then the manifest is generated from this properties file during build. I am going to implement this solution now.

Limiting the user to a subset of manifest configuration possibilities is an unfortunate consequence, but APDE was already doing this as part of the upgrade to Android mode 4.0. I may not get around to this right away, but one way to allow users to fully customize the manifest would be to have four different manifests in the sketch folder, one for each target. Then the user can choose to manage the manifest through properties or manually through the different manifest files. If a user is working on a large project, then it probably only has one target anyway.

**Comment by Calsign** [comment]
This should be fixed in v0.5.0-pre3.
