### ISSUE TITLE
Using APDE to run DCC++ Controller

### ISSUE THREAD

**Issue by EFA57** [Calsign/APDE#47]
I was trying to run DCC++ Controller but get 100+ errors
It appears that it can not find some libraries. 

Can it be used to compile and run DCC++ Controller.

If so what am I doing wrong or what do I need to add & where?

Thanks,

Erich

**Comment by Calsign** [comment]
I am assuming that you are referring to this repo: [DccPlusPlus/Controller](https://github.com/DccPlusPlus/Controller)

The problem is that the sketch is using the Processing serial library. The serial library is not supported in Android mode, see the [FAQ](https://github.com/Calsign/APDE/wiki#where-are-the-serial-network-video-or-sound-libraries). You might be able to use the AndroidSerial library (from that link) to replace the serial library, but I don't have any experience with this myself, so no guarantees.

**Comment by EFA57** [comment]
Thank You.
I will see if that & renaming the "call" works.

Erich

**Comment by Calsign** [comment]
Due to the inactivity I am assuming that you have figured things out. If you still have questions about using APDE then feel free to continue this thread, but this does not represent an actual issue with APDE so I am closing.
