### ISSUE TITLE
Installed app keeps stopping

### ISSUE THREAD

**Issue by RaspyHarmony101** [Calsign/APDE#50]
I recently created an app using APDE and it won't open. At first there were problems with the code and they were listed in the console, and I fixed all of them. When I run the sketch it installs fine and then a text box saying "(App) keeps stopping." pops up. I've tried uninstalling it and then running again and restarting my device. Not sure what to do in order for the app/sketch to work.

**Comment by EmmanuelPil** [comment]
@RaspyHarmony101 
Does this also happen with sample sketches?

**Comment by RaspyHarmony101** [comment]
No, none of the examples nor my other installed sketches act like this.

**Comment by Calsign** [comment]
@RaspyHarmony101 Your sketch is crashing. Just because the compiler doesn't give you an error doesn't mean that the sketch itself won't crash. Normally APDE will report the stack trace, but sometimes this fails.

If you have access to a computer you can look at LogCat directly for the stack trace. Or you can try removing parts of the code until you find the problematic part. You can probably get assistance at the Processing Forum assuming that your code isn't overly complicated:

http://forum.processing.org

**Comment by RaspyHarmony101** [comment]
Thanks, so what steps should i take in order to find the LogCat on my computer? (Currently I have the app on my tablet.)

**Comment by Calsign** [comment]
@RaspyHarmony101 To use LogCat, you need the [Android SDK tools](https://developer.android.com/studio/#downloads) on your computer. If you already have them then this should be easy, otherwise it might be more work than it's worth. You also need to [enable USB debugging](https://developer.android.com/studio/debug/dev-options).

Then run `adb logcat *:E | grep processing`. (Or use `findstr` instead of grep on Windows.)

**Comment by RaspyHarmony101** [comment]
(I apologize here if what I am about to say is unhelpful lol)
I looked to see how to implement your suggestion and I ran across how to read bugreports and similar things but I couldn't figure out how to look at it on my computer. Looking at the bug report from my tablet I found the following around the mentioning of the app, which I thought might be useful but I don't quite understand: 

java.lang.NullPointerException: Attempt to invoke virtual method 'void processing.core.PGraphics.textSize(float)' on a null object reference

**Comment by Calsign** [comment]
@RaspyHarmony101 For some reason your `textSize()` call is causing the problem. If you are just calling `textSize()` then you might be calling it too early (before the sketch gets created). If you are calling it on a PGraphics object then it might not be initialized. Either way, just try removing it for now.

**Comment by RaspyHarmony101** [comment]
Thank you for your help! It is working again!
