### ISSUE TITLE
Can't read Sketch Folder

### ISSUE THREAD

**Issue by RaspyHarmony101** [Calsign/APDE#53]
Whenever I click "Show Sketch Folder", a list of apps pop up that I am supposed to use to read the file. Is this suppose to happen? And, if so, what can I use/do to see what is in my app's folder?

**Comment by Calsign** [comment]
See #36.

Basically, Android doesn't have good support for viewing folders in a file manager. The only file manager that is currently known to support "show sketch folder" is OI File Manager. Otherwise you can navigate to the sketchbook folder in your favorite file manager, it should be on the external storage.
