### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by EmmanuelPil** [Calsign/APDE#90]
I have tested the new release and have several issues, but I'll post them one by one.
The first is; when I use settings I get the following error:
Code:

```
void settings() {
  fullScreen();
}

void setup (){
}

```
----------
2. ERROR in /data/data/com.calsignlabs.apde/app_build/src/processing/test/save_load_points/save_load_points.java (at line 87)
	public void settings() {
	            ^^^^^^^^^^
Duplicate method settings() in type save_load_points

Tested on Kitkat 4.4 and Lollipop
Samsung S4

**Comment by Calsign** [comment]
@EmmanuelPil Interesting. I'm surprised I haven't tested this to be honest.

This should be a pretty simple fix, not generating settings if it is already declared. I should be able to do it soon.

That being said, I'm a little surprised that you're using settings at all. You can put fullScreen into setup (because it doesn't use variables), or leave it out entirely (because APDE automatically adds it by default). It seems that the main reason for including settings would be for compatibility with desktop sketches? Or am I missing some use case here?

Thanks for testing this out, I really appreciate the feedback.

**Comment by EmmanuelPil** [comment]
>  I'm a little surprised that you're using settings at all

It seems that loading an app to the play store is not possible with current mode  A4P PC
But APDE does, however using settings() See [here](https://discourse.processing.org/t/changing-targetsdkversion/14723/21?u=noelrl)
That's why I use it.
The second error I had in most of my sketches was

> Syntax error on token "Invalid Character", delete this token

But after cleaning those "invisible" characters all is well, so it isn't actually an error, but this version is more demanding.

**Comment by Calsign** [comment]
@EmmanuelPil I see.

Do you know what the jnvalid whitespace character is (newline, tab, something else)? Could you send me a sample file that has the invalid characters?

**Comment by EmmanuelPil** [comment]
[Here](https://drive.google.com/open?id=1J28IGA2d5T2V4qFTa6q38QfhJPiz4D52) is a link to a function in sketch displaying invalid character.
I've compared an original with a corrected sketch in a hex editor.
This is the result of the first lines.

-       ***  Comparing A:	/storage/emulated/0/Sketchbook/wrongchar/sketch.pde 	   * regular file * 487 bytes * last status change: 2020-05-18.09:07:54 * last file modification: 2020-05-18.09:07:54 * mode [octal]: 100770     
+       ***  With B:   		/storage/emulated/0/Sketchbook/betterchar/sketch.pde 	   * regular file * 481 bytes * last status change: 2020-05-18.09:10:21 * last file modification: 2020-05-18.09:10:21 * mode [octal]: 100770     
 000000  76 6f 69 64 20 73 61 76 65 49 6d 61 67 65 28 53 void saveImage(S     
 000010  74 72 69 6e 67 20 73 29 20 7b 0a 20 20          tring s) {     
-00001D  c2 a0                                                
 00001D  74 72 79 20 7b 0a 20 20 20 20                   try {     
-000029  c2 a0                                                
 000027  53 74 72 69 6e 67 20 64 69 72 65 63 74 6f 72 79 String directory     

It seems to have something to do with


"=C2=A0" represents the bytes C2 A0. However, since this is UTF-8, it translates to 00A0, which is the Unicode for non-breaking space.

**Comment by Calsign** [comment]
@EmmanuelPil Hmm.

At first glance I can just replace all non-breaking spaces with regular spaces, just like it replaces CRLF newlines with LF. But on second thought this might not be the best idea, because non-breaking spaces are valid characters in Java strings and such an approach would be confusing for people that perhaps legitimately wanted to use non-breaking spaces in their strings.

I'm mostly surprised that these characters used to be accepted by APDE. They also appear to be rejected by the desktop PDE. As such I think rejecting them as invalid characters is the correct behavior (perhaps more correct than older versions of APDE).

If there's something I'm missing then please feel free to correct me, but this seems to be working as expected.

**Comment by EmmanuelPil** [comment]
> As such I think rejecting them as invalid characters is the correct behavior (perhaps more correct than older versions of APDE).

I agree.
My projects are quite large, so when about 20% of the code was red-underlined, it scared me. Most of  the errors along  the described above were of the type:: 


>  bluetooth [54]: Syntax error on token "}", delete this token
> The method onResume(l is undefined for the type ListView
>  bt cannot be resolved
> draw [255]: The method header() is undefined for the type pcg15

It just didn't make sense.  I solved it by opening a new sketch and copy/pasting it, from the original sketch, tab by tab.
Since the popup menu Commment/Uncomment function does not work (and I use this a lot for debugging), I use external editors, and I think it´s there where the copying of invalid characters comes from.
So after all, taking away the settings() issue it's all OK.
Thank you for another greatly improved release.
