### ISSUE TITLE
Feature request: Streamline DEX

### ISSUE THREAD

**Issue by uheinema** [Calsign/APDE#92]
Hello, here is my Daily Terror:

As I develop libraries with APDE, and keep them in the Sketchbook/libraries/ folder for convenience/testing, I quite often have to:
- copy .class files from build/bin into the Sketchbook/libraries/MyLib/library/MyLib.jar (TotalCommander)
- in APDE
- - Open Tools/Import lib/Manage/Dex
- - Select above jar
- - Enter/copy/select jar-dex
- - -  Delete previous jar-dex 
- - DEX it, Hurray!

# Wish1: Only warn on existing target

# Wish2: On selecting jar, offer to reimport new .class files from build/bin, if existing.

# Dream: At the Library list, add to the (pretty useless) menu holding 'Uninstall'

'Re-dex'
 - select this as the jar  and jar-dex files
 - Wish 2
 - Wish 1

Just an idea..

Best regards

**Comment by Calsign** [comment]
First, I'm surprised that you're able to develop libraries in APDE, I thought this was normally done with a full Java IDE like Eclipse. Not that what you're doing is wrong, I'm just surprised.

I don't plan to support a full library development pipeline in APDE, but I think some of these things are doable.

 - I don't know what you mean by "only warn on existing target".
 - Offering to re-import the .class files from build/bin seems a bit involved to support a very non-conventional workflow, but it might be doable. (This doesn't mean I will actually implement it, we'll have to see.)
 - Making a "re-dex library" option (run dx dexer on an existing library from the menu) seems very feasible, in fact I could probably implement it in ten minutes. In fact I probably will in a couple of days for the new release because it seems useful for other use cases, like assisting in manually installing libraries.

Perhaps I am misunderstanding what you're saying.

Also, it seems like you're hacking around in APDE's internals a bit. If you are so inclined, you are welcome to implement these changes yourself, and if you make a reasonable pull request I will merge it.

**Comment by EmmanuelPil** [comment]
>for the new release 

If it's not too much, please consider the un/comment fix.  :+1:

**Comment by uheinema** [comment]
Hello,
1. Started with librarys per chance, was looking at build/bin out of curiosity, and found the .class files...A .jar is just  zip, noone needs manifests...Dexter is available...so I gave ot a try. Worked.

2. Actually I don't even own a PC...

3. Biilding libtaries is surely not worth much effort in UI integration, but please don't take away the possibility. (Like hiding 'build' as 'no user ever looks there' and 'to improve customer service'...have seen such things a few times .)

4. 'Existing targets': The DEX inteface now complains 'Output file must not exist' and won't let you run DX before
  - deleting it (ouTside of APDE)
 -  going back and 'touching' the input field.
It's not a feature, it's an annoyance.
The re-dex (sans .class-copying) , if easy to do, would be great.

**Comment by uheinema** [comment]
I am an Android - noob, just trying to solve some self-inflicted problems ;-)
And, see above, no PC. If it cannot be done with APDE, it will not be done at all :-)
So a correct pull might not happen so soon.
Next might be to write my tutorial on library creatiiOn with APDE, maybe in/for your wiki?

Anyhow, tnx  again!

**Comment by uheinema** [comment]
Here you are:

https://github.com/uheinema/Building-processing-libs-with-APDE/blob/master/README.md

**Comment by uheinema** [comment]
Hello again,
hope you are well?

If you had plans on changing the UI, and have not implemented them, drop it...
Meanwhile I can live with running dx from Termux, updated above tutorial to explain how.

But PLEASE consider #95 !

Best regards
Ullrich
